  default: &default
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    timeout: 5000
    host: 127.0.0.1
    port: 5432
    username:
    password:

  development:
    <<: *default
    database: revvedhr_development

  test:
    <<: *default
    database: revvedhr_test

  # DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
  production:
    url: <%= ENV['DATABASE_URL'] %>
